"""Appendix table of the transplanted sets (W82-W85), one row per arm, from the run index.
  python ICLR/ICLR_quantization/tables/make_tab_sets.py   (from the repo root)
"""
import csv
import os

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
os.chdir(ROOT)
OUT = 'ICLR/ICLR_quantization/tables/tab_sets.tex'
idx = {r['tag']: float(r['avg4']) for r in csv.DictReader(open('runs/INDEX_scores.csv')) if r.get('avg4')}


def v(tag):
    return f'{idx[tag]:.3f}'


ROWS = [
    ('\\multicolumn{3}{l}{\\emph{Llama-3.1-8B, collapsed short-document GPTQ3 network (\\LgptqIF{}), layers $k$ onward re-rounded to nearest}}', None, None),
    ('$k=2$ / 4 / 8 / 16 / 24', None, ' / '.join(v(f'f_l_rtntail_{k}') for k in (2, 4, 8, 16, 24))),
    ('\\multicolumn{3}{l}{\\emph{Into the RTN3 Llama (\\LrtnIF{}), from the collapsing draw (seed 0)}}', None, None),
    ('(1, down)', 'the lesion alone', v('f_tp_l_rtn_les')),
    ('(0, down)', 'the layer-0 down-projection alone', v('f_tp_l_rtn_L0down')),
    ('(0, down) + (1, down)', 'the pair', v('f_tp_l_rtn_L01down')),
    ('layer 0 all + (1, down)', '8 matrices', v('f_tp_l_rtn_L0all_les')),
    ('layers 0--1 all', '14 matrices', v('f_tp_l_rtn_L01all')),
    ('layer 1 all', '7 matrices, lesion inside', v('f_tp_l_rtn_L1all')),
    ('layer 1 MLP', 'gate, up, down', v('f_tp_l_rtn_L1mlp')),
    ('layer 1 attention + (1, down)', '', v('f_tp_l_rtn_L1attn_les')),
    ('layer 0 attention + (1, down)', '', v('f_tp_l_rtn_L0attn_les')),
    ('layer 0 gate, up + (1, down)', '', v('f_tp_l_rtn_L0mlp_les')),
    ('\\multicolumn{3}{l}{\\emph{Into the RTN3 Llama, from the healthy draw (seed 1, \\LgptqSeedIF{})}}', None, None),
    ('(0, down) + (1, down)', 'the pair', v('f_tp_l_rtn_cs1_L01down')),
    ('layers 0--1 all', '14 matrices', v('f_tp_l_rtn_cs1_L01all')),
    ('\\multicolumn{3}{l}{\\emph{Into the collapsed short-document Llama, from the window-calibrated (c4win) network}}', None, None),
    ('(0, down)', '', v('f_tp_l_short_cwinL0')),
    ('(1, down)', '', v('f_tp_l_c4_c4winles')),
    ('(0, down) + (1, down)', '', v('f_tp_l_short_cwinL01')),
    ('\\multicolumn{3}{l}{\\emph{Excision inside the collapsed short-document Llama (re-rounded to nearest, everything else GPTQ)}}', None, None),
    ('(0, down) / (1, down) / both', '', ' / '.join(v(t) for t in ('f_l_rtn0down', 'f_l_rtn1down', 'f_l_rtn01down'))),
    ('\\multicolumn{3}{l}{\\emph{Into the RTN3 Tulu-3 (\\TuluRtnIF{}; its GPTQ3 network is healthy, \\TuluGptqIF{})}}', None, None),
    ('(0, down) + (1, down)', 'its own pair', v('f_tp_tulu3_rtn_L01down')),
    ('\\multicolumn{3}{l}{\\emph{Into the RTN3 Qwen2.5-14B (\\QrtnIF{})}}', None, None),
    ('(4, down)', 'the lesion, short documents', v('f_tp_q14_rtn_L4down')),
    ('(4, down)', 'the same matrix from the window-calibrated network', v('f_tp_q14_rtn_cwinL4down')),
    ('(4, down) + (5, down)', '', v('f_tp_q14_rtn_L45down')),
    ('both excised in the GPTQ network', '', v('f_q14_rtn45down')),
    ('\\multicolumn{3}{l}{\\emph{Into the RTN3 Mistral-7B-v0.3 (\\MrtnIF{}), from its collapsed window-calibrated network (\\MgptqIF{})}}', None, None),
    ('(1, down)', '', v('f_tp_m7_rtn_L1down')),
    ('(0, down) + (1, down)', '', v('f_tp_m7_rtn_L01down')),
    ('layers 0--3 down', '4 matrices', v('f_tp_m7_rtn_L03down')),
    ('layer 1 all', '7 matrices', v('f_tp_m7_rtn_L1all')),
    ('layers 0--1 all', '14 matrices', v('f_tp_m7_rtn_L01all')),
    ('layers 0--3 all', '28 matrices', v('f_tp_m7_rtn_L03all')),
]
with open(OUT, 'w', encoding='utf-8') as f:
    f.write('% generated by tables/make_tab_sets.py; do not edit by hand\n')
    f.write('\\begin{table}[htbp]\n\\caption{Which matrices the collapse needs (\\cref{sec:lesion}). Fixed-matrix transplants: the named '
            'matrices of a donor checkpoint replace the same matrices of a target network, everything else in the target unchanged; '
            '$(\\ell,\\text{down})$ is the down-projection of layer $\\ell$. IFEval, 3 bits, group 128.}\n'
            '\\label{tab:sets}\n\\begin{center}\n\\footnotesize\n\\begin{tabular}{>{\\raggedright\\arraybackslash}p{4.6cm}>{\\raggedright\\arraybackslash}p{4.8cm}r}\n\\toprule\n'
            'Transplanted set & & IFEval \\\\\n\\midrule\n')
    for a, b, c in ROWS:
        if b is None and c is None:
            f.write(a + ' \\\\\n')
        elif len(c) > 8:   # several values: span the middle and the right column
            f.write(f'\\quad {a} & \\multicolumn{{2}}{{l}}{{{c}}} \\\\\n')
        else:
            f.write(f'\\quad {a} & {b or ""} & {c} \\\\\n')
    f.write('\\bottomrule\n\\end{tabular}\n\\end{center}\n\\end{table}\n')
print('wrote', OUT, len(ROWS), 'rows')
