"""Appendix D.1: the full per-model census, one row per model, from the run index.

  python ICLR/ICLR_quantization/tables/make_census_full.py     (from the repo root)
writes tables/tab_census_full.tex and prints the sanity checks that the census
macros of 00_numbers.tex rest on (worst corrected-vs-RTN, healthy-model mean).

Columns: sink layer, A_BOS, G_BOS at that layer (runs/sides/<key>_c4.csv, fp16),
kappa at that layer (runs/theory/f_<key>_c4.json, W76), then IFEval of fp16, RTN3,
GPTQ3 short documents, corrected objective, GPTQ3 C4 windows, GPTQ4, RTN4
(runs/INDEX_scores.csv; fixed-code f_* arms for everything GPTQ, RTN and fp16 from
the runs named in RTN3/FP16 below, which the loop correction does not touch).
"""
import csv
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
os.chdir(ROOT)
OUT = 'ICLR/ICLR_quantization/tables/tab_census_full.tex'

MODELS = [  # key, display name, params
    ('l', 'Llama-3.1-8B-Instruct', '8B'), ('q14', 'Qwen2.5-14B-Instruct', '14B'),
    ('m7', 'Mistral-7B-Instruct-v0.3', '7B'), ('q7', 'Qwen2.5-7B-Instruct', '7B'),
    ('q32', 'Qwen2.5-32B-Instruct', '32B'), ('q3', 'Qwen2.5-3B-Instruct', '3B'),
    ('nemo', 'Mistral-Nemo-Instruct', '12B'), ('g29', 'gemma-2-9b-it', '9B'),
    ('l3', 'Llama-3-8B-Instruct', '8B'), ('l32', 'Llama-3.2-3B-Instruct', '3B'),
    ('f3', 'Falcon3-7B-Instruct', '7B'), ('sm', 'SmolLM2-1.7B-Instruct', '1.7B'),
    ('hermes3', 'Hermes-3-Llama-3.1-8B', '8B'), ('ministral', 'Ministral-8B-Instruct', '8B'),
    ('qwen3_14b', 'Qwen3-14B', '14B'), ('tulu3', 'Llama-3.1-Tulu-3-8B', '8B'),
    ('qwen3_8b', 'Qwen3-8B', '8B'), ('granite', 'granite-3.1-8b-instruct', '8B'),
]
# RTN3 and fp16 runs (sym, group 128), with the run that produced each value
RTN3 = {'l': 'rtn3l_none', 'q14': 'rtn3q14_none', 'm7': None, 'q7': 'rtn3q_none', 'q32': 'h_q32_rtn',
        'q3': 'rtn3q3_none', 'nemo': 'h_nemo_rtn', 'g29': 'cens_g2_9b_rtn3', 'l3': 'f_l3_rtn3',
        'l32': 'f_l32_rtn3', 'f3': 'cens_f3_7b_rtn3', 'sm': 'cens_sm_1p7b_rtn3',
        'hermes3': 'blind_hermes3_8b_rtn3', 'ministral': 'blind_ministral_8b_rtn3',
        'qwen3_14b': 'blind_qwen3_14b_rtn3', 'tulu3': 'f_tulu3_rtn3', 'qwen3_8b': 'blind_qwen3_8b_rtn3',
        'granite': 'blind_granite31_8b_rtn3'}
RTN3_FIXED = {'m7': 0.420}          # W7 run, recorded in RESULTS/jobs (jobs/w26_induce.sh); not in the index
FP16 = {'l': 'qbase_llama_fp16', 'q14': 'qbase_qwen14_fp16', 'm7': 'qbase_mistral_fp16',
        'q7': 'qbase_fp16', 'q32': 'qbase_qwen32_fp16', 'q3': 'cens_q25_3b_fp16', 'nemo': 'cens_nemo_12b_fp16',
        'g29': 'cens_g2_9b_fp16', 'l3': 'cens_l3_8b_fp16', 'l32': 'cens_l32_3b_fp16', 'f3': 'cens_f3_7b_fp16',
        'sm': 'cens_sm_1p7b_fp16'}

idx = {}
for r in csv.DictReader(open('runs/INDEX_scores.csv')):
    if r.get('avg4'):
        idx[r['tag']] = float(r['avg4'])
# archived runs the index does not carry
for tag in ('rtn3q_none', 'rtn3q3_none'):
    p = f'runs_archive/scores/scores_{tag}.csv'
    if tag not in idx and os.path.exists(p):
        idx[tag] = float(next(csv.DictReader(open(p)))['avg4'])


def score(tag):
    return idx.get(tag) if tag else None


def sides(key):
    p = f'runs/sides/{key}_c4.csv'
    rows = [r for r in csv.DictReader(open(p)) if r['proj'] == 'down_proj']
    best = max(rows, key=lambda r: float(r['A_bos']))
    return int(best['layer']), float(best['A_bos']), float(best['G_bos'])


def kappa(key):
    p = f'runs/theory/f_{key}_c4.json'
    if not os.path.exists(p):
        return None
    recs = json.load(open(p))
    recs = recs if isinstance(recs, list) else [recs]
    s = next((r for r in recs if r.get('role') == 'sink'), None)
    return s['kappa'] if s else None


def f3(v):
    return '---' if v is None else f'{v:.3f}'


def sci(v):
    if v is None:
        return '---'
    e = int(f'{v:.0e}'.split('e')[1])
    m = v / 10 ** e
    return f'${m:.1f}\\times10^{{{e}}}$' if e >= 3 else f'{v:.0f}'


rows, checks = [], []
for key, name, size in MODELS:
    L, a, g = sides(key)
    k = kappa(key)
    fp = score(FP16.get(key))
    rtn = RTN3_FIXED.get(key, score(RTN3.get(key)))
    gptq, corr, cwin = score(f'f_{key}_none'), score(f'f_{key}_gwtn'), score(f'f_{key}_c4win')
    g4, r4 = score(f'f_{key}_gptq4'), score(f'u4_{key}_rtn4')
    rows.append((name, size, L, a, g, k, fp, rtn, gptq, corr, cwin, g4, r4))
    if rtn is not None and corr is not None:
        checks.append((name, round(100 * (corr - rtn), 1), round(100 * (corr - gptq), 1), round(100 * (gptq - rtn), 1)))

with open(OUT, 'w', encoding='utf-8') as f:
    f.write('% generated by tables/make_census_full.py; do not edit by hand\n')
    f.write('\\begin{table}[htbp]\n')
    f.write('\\caption{The census, one row per model (\\cref{sec:universality}). Sink layer, $A_{\\bos}$ and $G_{\\bos}$ are '
            'measured on the full-precision model at its most \\bos{}-dominated down-projection (128 C4 documents); '
            '$\\kappa=\\vx_0^\\top\\mM^{-1}\\vx_0$ of \\cref{thm:rankone} at that matrix. IFEval (mean of four accuracies) '
            'at 3 bits for fp16, RTN, GPTQ under short documents, the corrected objective under short documents and GPTQ '
            'under C4 windows, then 4-bit GPTQ and RTN; group size 128 throughout. gemma-2-9b has no sink-dominated layer; '
            'its row gives the largest $A_{\\bos}$ found. RTN and fp16 values come from runs that the loop correction of '
            '\\cref{app:protocols} does not affect; a dash is a run we do not have.}\n')
    f.write('\\label{tab:census_full}\n\\begin{center}\n\\scriptsize\n\\setlength{\\tabcolsep}{3.5pt}\n')
    f.write('\\begin{tabular}{llrrrrrrrrrrr}\n\\toprule\n')
    f.write('Model & Size & Layer & $A_{\\bos}$ & $G_{\\bos}$ & $\\kappa$ & fp16 & RTN3 & GPTQ3 & Corr. & c4win & GPTQ4 & RTN4 \\\\\n\\midrule\n')
    for (name, size, L, a, g, k, fp, rtn, gptq, corr, cwin, g4, r4) in rows:
        f.write(f'{name} & {size} & {L} & {a:.3f} & {g:.3f} & {sci(k)} & {f3(fp)} & {f3(rtn)} & {f3(gptq)} & '
                f'{f3(corr)} & {f3(cwin)} & {f3(g4)} & {f3(r4)} \\\\\n')
    f.write('\\bottomrule\n\\end{tabular}\n\\end{center}\n\\end{table}\n')
print('wrote', OUT, len(rows), 'rows')

print('\nsanity checks against 00_numbers.tex census macros:')
worst = min(checks, key=lambda c: c[1])
print('  corrected - RTN3 worst: %s %+.1f   (macro CorrWorstVsRTN says -4.6, gemma-2-9b)' % (worst[0], worst[1]))
healthy = [c for c in checks if c[0] not in ('Llama-3.1-8B-Instruct', 'Qwen2.5-14B-Instruct')]
m = sum(c[2] for c in healthy) / len(healthy)
print('  corrected - GPTQ3 on %d non-collapsing models: mean %+.1f (macro +0.3), worst %+.1f, best %+.1f (macros -5.6 / +13.9)'
      % (len(healthy), m, min(c[2] for c in healthy), max(c[2] for c in healthy)))
print('  GPTQ3 - RTN3 per model:', sorted(((c[0][:14], c[3]) for c in checks), key=lambda x: x[1]))
